name: primihub CI/CD actions

on:
  push:
    branches:
     - sync2gitee # for test
  #   # Publish semver tags as releases.
  #   tags: [ '*' ]
  pull_request:
    branches:
      - develop

jobs:

  build-on-mac-amd64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Setup bazelisk
      uses: bazelbuild/setup-bazelisk@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install gettext
      run: brew install gettext
    - name: Add libintl to DYLD_FALLBACK_LIBRARY_PATH
      run: echo '/usr/local/opt/gettext/lib' | sudo tee -a /etc/paths.d/libintl.dylib
    - name: set PYTHON LINK_OPTS
      run: ./pre_build.sh
      shell: bash
    - name: bazel build
      run: |
        # cc_binary
        bazel build --config=darwin_x86_64 //:node \
            //:py_main \
            //:cli \
            //src/primihub/pybind_warpper:opt_paillier_c2py \
            //src/primihub/pybind_warpper:linkcontext

