name: primihub CI/CD actions

on:
  push:
    branches:
     - sync2gitee # for test
  #   # Publish semver tags as releases.
  #   tags: [ '*' ]
  pull_request:
    branches:
      - develop

jobs:

  build-on-mac-amd64:
    runs-on: macos-12.0
    steps:
    - uses: actions/checkout@v3
    - name: Setup bazelisk
      uses: bazelbuild/setup-bazelisk@v2
    - name: set PYTHON LINK_OPTS
      run: ./pre_build.sh
      shell: bash
    - name: bazel build
      run: |
        # cc_binary
        bazel build --config=darwin_x86_64 //:node \
            //:py_main \
            //:cli \
            //src/primihub/pybind_warpper:opt_paillier_c2py \
            //src/primihub/pybind_warpper:linkcontext

